\hypertarget{classnumpy_1_1testing_1_1__private_1_1utils_1_1KnownFailureException}{}\section{numpy.\+testing.\+\_\+private.\+utils.\+Known\+Failure\+Exception Class Reference}
\label{classnumpy_1_1testing_1_1__private_1_1utils_1_1KnownFailureException}\index{numpy.\+testing.\+\_\+private.\+utils.\+Known\+Failure\+Exception@{numpy.\+testing.\+\_\+private.\+utils.\+Known\+Failure\+Exception}}


Inheritance diagram for numpy.\+testing.\+\_\+private.\+utils.\+Known\+Failure\+Exception\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=220pt]{classnumpy_1_1testing_1_1__private_1_1utils_1_1KnownFailureException__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for numpy.\+testing.\+\_\+private.\+utils.\+Known\+Failure\+Exception\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=220pt]{classnumpy_1_1testing_1_1__private_1_1utils_1_1KnownFailureException__coll__graph}
\end{center}
\end{figure}


\subsection{Detailed Description}
\begin{DoxyVerb}Raise this exception to mark a test as a known failing test.\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/lib/python3.\+9/site-\/packages/numpy/testing/\+\_\+private/\hyperlink{numpy_2testing_2__private_2utils_8py}{utils.\+py}\end{DoxyCompactItemize}
