\hypertarget{classnetworkx_1_1exception_1_1ExceededMaxIterations}{}\section{networkx.\+exception.\+Exceeded\+Max\+Iterations Class Reference}
\label{classnetworkx_1_1exception_1_1ExceededMaxIterations}\index{networkx.\+exception.\+Exceeded\+Max\+Iterations@{networkx.\+exception.\+Exceeded\+Max\+Iterations}}


Inheritance diagram for networkx.\+exception.\+Exceeded\+Max\+Iterations\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=228pt]{classnetworkx_1_1exception_1_1ExceededMaxIterations__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for networkx.\+exception.\+Exceeded\+Max\+Iterations\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=228pt]{classnetworkx_1_1exception_1_1ExceededMaxIterations__coll__graph}
\end{center}
\end{figure}


\subsection{Detailed Description}
\begin{DoxyVerb}Raised if a loop iterates too many times without breaking.

This may occur, for example, in an algorithm that computes
progressively better approximations to a value but exceeds an
iteration bound specified by the user.\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/lib/python3.\+9/site-\/packages/networkx/\hyperlink{exception_8py}{exception.\+py}\end{DoxyCompactItemize}
