\hypertarget{classnetworkx_1_1exception_1_1NetworkXAlgorithmError}{}\section{networkx.\+exception.\+Network\+X\+Algorithm\+Error Class Reference}
\label{classnetworkx_1_1exception_1_1NetworkXAlgorithmError}\index{networkx.\+exception.\+Network\+X\+Algorithm\+Error@{networkx.\+exception.\+Network\+X\+Algorithm\+Error}}


Inheritance diagram for networkx.\+exception.\+Network\+X\+Algorithm\+Error\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=350pt]{classnetworkx_1_1exception_1_1NetworkXAlgorithmError__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for networkx.\+exception.\+Network\+X\+Algorithm\+Error\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=221pt]{classnetworkx_1_1exception_1_1NetworkXAlgorithmError__coll__graph}
\end{center}
\end{figure}


\subsection{Detailed Description}
\begin{DoxyVerb}Exception for unexpected termination of algorithms.\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/lib/python3.\+9/site-\/packages/networkx/\hyperlink{exception_8py}{exception.\+py}\end{DoxyCompactItemize}
