\hypertarget{classnetworkx_1_1exception_1_1NetworkXUnfeasible}{}\section{networkx.\+exception.\+Network\+X\+Unfeasible Class Reference}
\label{classnetworkx_1_1exception_1_1NetworkXUnfeasible}\index{networkx.\+exception.\+Network\+X\+Unfeasible@{networkx.\+exception.\+Network\+X\+Unfeasible}}


Inheritance diagram for networkx.\+exception.\+Network\+X\+Unfeasible\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=350pt]{classnetworkx_1_1exception_1_1NetworkXUnfeasible__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for networkx.\+exception.\+Network\+X\+Unfeasible\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=221pt]{classnetworkx_1_1exception_1_1NetworkXUnfeasible__coll__graph}
\end{center}
\end{figure}


\subsection{Detailed Description}
\begin{DoxyVerb}Exception raised by algorithms trying to solve a problem
instance that has no feasible solution.\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
venv/lib/python3.\+9/site-\/packages/networkx/\hyperlink{exception_8py}{exception.\+py}\end{DoxyCompactItemize}
